apiVersion: v1
kind: Service
metadata:
  labels:
    app: javaapp1
  name: javaapp1
spec:
  type: NodePort
  ports:
    - port: 8005
      targetPort: 8005
      protocol: TCP
  selector:
    app: javaapp1
